this is about exceptions in python
